# Use postgres/example user/password credentials

services:

  db:
    container_name: Sistema_de_users
    image: postgres
    restart: always
    
    shm_size: 128mb
    
    volumes:
      - type:/tmpfs
  
    
    environment:
      POSTGRES_PASSWORD: ${SECRET_KEY}
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${DB}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  type: